"""Retrieval information page — ask questions and inspect retrieved context."""
from __future__ import annotations

import os

import streamlit as st

from rag.embeddings import EmbeddingModel
from rag.llm import generate_answer, list_models

# Static fallback shown if the live model lookup fails.
# The dropdown is replaced with the key's real available models once possible,
# since Groq periodically retires/restricts model ids.
FALLBACK_MODELS = [
    "llama-3.1-8b-instant",
    "llama-3.3-70b-versatile",
    "gemma2-9b-it",
]

api_key = os.environ.get("GROQ_API_KEY", "")

st.title("Retrieval information")
st.caption("Ask questions about your indexed documents. Answers are generated by Groq using only retrieved excerpts.")

if not api_key:
    st.error(
        "GROQ_API_KEY is not set. Copy `.env.example` to `.env`, add your key "
        "(get one free at console.groq.com), and restart the app."
    )
    st.stop()


@st.cache_data(ttl=300, show_spinner=False)
def _fetch_models(key: str) -> list[str]:
    try:
        return list_models(key)
    except Exception:
        return []


with st.expander("Settings", icon=":material/tune:"):
    live_models = _fetch_models(api_key)
    model_options = live_models or FALLBACK_MODELS
    if not live_models:
        st.caption("Couldn't fetch your available models; showing common defaults.")
    model = st.selectbox("Groq model", model_options, index=0)
    top_k = st.slider("Chunks to retrieve", min_value=2, max_value=8, value=4)

store = st.session_state.vector_store

for turn in st.session_state.qa_log:
    with st.chat_message("user"):
        st.markdown(turn["question"])
    with st.chat_message("assistant"):
        st.markdown(turn["answer"])
        if turn["sources"]:
            with st.expander("Sources"):
                for text, source, score in turn["sources"]:
                    st.markdown(f"**{source}** (similarity: {score:.2f})")
                    st.text(text[:500] + ("..." if len(text) > 500 else ""))

question = st.chat_input("Ask a question about your document...")

if question:
    if not store or store.is_empty:
        st.error("Upload and process at least one document first, on the Upload documents page.")
    else:
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):
            with st.spinner("Retrieving relevant excerpts and generating answer..."):
                embedder = EmbeddingModel()
                query_vector = embedder.embed([question])[0]
                results = store.search(query_vector, top_k=top_k)
                context_chunks = [(c.text, c.source, score) for c, score in results]

                try:
                    answer = generate_answer(
                        api_key=api_key,
                        model=model,
                        question=question,
                        context_chunks=context_chunks,
                        chat_history=st.session_state.chat_history[-6:],
                    )
                except Exception as e:
                    answer = f"Error calling Groq API: {e}"

            st.markdown(answer)
            if context_chunks:
                with st.expander("Sources"):
                    for text, source, score in context_chunks:
                        st.markdown(f"**{source}** (similarity: {score:.2f})")
                        st.text(text[:500] + ("..." if len(text) > 500 else ""))

        st.session_state.chat_history.append({"role": "user", "content": question})
        st.session_state.chat_history.append({"role": "assistant", "content": answer})
        st.session_state.qa_log.append(
            {"question": question, "answer": answer, "sources": context_chunks}
        )
